[workspace]
members = ["plugins/*"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
log = "0.4"
tauri = { branch = "v1.3", git = "https://github.com/luoffei/tauri"}
tauri-build = { branch = "v1.3", git = "https://github.com/luoffei/tauri"}
serde_json = "1"
thiserror = "1"

[workspace.package]
edition = "2021"
authors = [ "Tauri Programme within The Commons Conservancy" ]
license = "Apache-2.0 OR MIT"
rust-version = "1.64"
